#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""The setup script."""

from setuptools import setup, find_packages

with open('README.md') as readme_file:
    readme = readme_file.read()

with open('HISTORY.md') as history_file:
    history = history_file.read()

install_requirements = [
    'adal==1.0.2',
    'aiohttp==2.3.10',
    'aniso8601==3.0.2',
    'argh==0.26.2',
    'asn1crypto==0.24.0',
    'async-timeout==3.0.0',
    'attrdict==2.0.0',
    'attrs==18.1.0',
    'certifi==2018.8.13',
    'cffi==1.11.5',
    'chardet==3.0.4',
    'click==6.7',
    'coincurve==8.0.2',
    'coloredlogs==10.0',
    'cytoolz==0.9.0.1',
    'eciespy==0.1.2',
    'eth-abi==1.1.1',
    'eth-account==0.3.0',
    'eth-hash==0.1.4',
    'eth-keyfile==0.5.1',
    'eth-keys==0.2.0b3',
    'eth-rlp==0.1.2',
    'eth-typing==1.1.0',
    'eth-utils==1.2.0',
    'Flask==1.0.2',
    'Flask-Cors==3.0.6',
    'Flask-RESTful==0.3.6',
    'flask-swagger==0.2.13',
    'flask-swagger-ui==3.6.0',
    'futures==3.1.1',
    'gunicorn==19.9.0',
    'hexbytes==0.1.0',
    'humanfriendly==4.16.1',
    'idna==2.7',
    'idna-ssl==1.1.0',
    'isodate==0.6.0',
    'itsdangerous==0.24',
    'Jinja2==2.10',
    'jsonschema==2.5.1',
    'keeper-contracts==0.1.1',
    'logstats==0.2.1',
    'lru-dict==1.1.6',
    'MarkupSafe==1.0',
    'mccabe==0.6.1',
    'msrest==0.5.4',
    'multidict==4.3.1',
    'multipipes==0.1.0',
    'oauthlib==2.1.0',
    'squid-py==0.2.1',
    'oceandb-driver-interface==0.1.11',
    'oceandb-mongodb-driver==0.1.3',
    'oceandb-elasticsearch-driver==0.0.2',
    # 'oceandb-bigchaindb-driver==0.1.3',
    'parsimonious==0.8.0',
    'pathtools==0.1.2',
    'pkginfo==1.4.2',
    'pluggy==0.6.0',
    'py==1.5.4',
    'py-solc==3.1.0',
    'pycodestyle==2.3.1',
    'pycparser==2.18',
    'pycryptodome==3.6.6',
    'pycryptodomex==3.6.6',
    'PyJWT==1.6.4',
    'pymongo==3.7.1',
    'PyNaCl==1.1.2',
    'pyOpenSSL==18.0.0',
    'pysha3==1.0.2',
    'python-dateutil==2.7.3',
    'python-rapidjson-schema==0.1.1',
    'pytz==2018.5',
    'PyYAML==3.13',
    'requests==2.20.0',
    'requests-oauthlib==1.0.0',
    'requests-toolbelt==0.8.0',
    'rethinkdb==2.3.0.post6',
    'rlp==1.0.2',
    'semantic-version==2.6.0',
    'singletonify==0.1.2.0',
    'six==1.11.0',
    'statsd==3.2.1',
    'toolz==0.9.0',
    'tqdm==4.25.0',
    'urllib3==1.23',
    'websockets==5.0.1',
    'Werkzeug==0.14.1',
    'yarl==1.2.6',
]

setup_requirements = ['pytest-runner==2.11.1', ]

dev_requirements = [
    'bumpversion==0.5.3',
    'twine==1.11.0',
    # not virtualenv: devs should already have it before pip-installing
    'watchdog==0.8.3',
]

test_requirements = [
    'codacy-coverage==1.3.11',
    'coverage==4.5.1',
    'flake8==3.5.0',
    'pyflakes==1.6.0',
    'pytest==3.4.2',
    'tox==3.2.1',
]

setup(
    author="leucothia",
    author_email='devops@oceanprotocol.com',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ],
    description="🐳 Ocean aquarius.",
    extras_require={
        'test': test_requirements,
        'dev': dev_requirements + test_requirements,
    },
    include_package_data=True,
    install_requires=install_requirements,
    keywords='ocean-aquarius',
    license="Apache Software License 2.0",
    long_description=readme,
    long_description_content_type="text/markdown",
    name='ocean-aquarius',
    packages=find_packages(include=['aquarius', 'aquarius.app']),
    setup_requires=setup_requirements,
    test_suite='tests',
    tests_require=test_requirements,
    url='https://github.com/oceanprotocol/aquarius',
    version='0.1.2',
    zip_safe=False,
)
