#!/bin/bash -x
#PROVIDERDIR=.
CONF_FILE=oceandb.ini
#KEEPERDIR=~/Projects/keeper-contracts
#cd $KEEPERDIR

result=$(docker exec -it docker_keeper-contracts_1 truffle migrate --reset | grep -P 'OceanMarket:|OceanToken:|OceanAuth:')
values=$(echo $result | sed 's/OceanToken: /token.address=/' | sed 's/OceanMarket: /\nmarket.address=/' | sed 's/OceanAuth: /\nauth.address=/')
token=$(echo $values | cut -d' ' -f1)
market=$(echo $values | cut -d' ' -f2)
auth=$(echo $values | cut -d' ' -f3)
#cp -R $KEEPERDIR/build/contracts $PROVIDERDIR/venv/contracts
sed -i -e "/token.address=/c ${token}" $CONF_FILE
sed -i -e "/market.address=/c ${market}" $CONF_FILE
sed -i -e "/auth.address=/c ${auth}" $CONF_FILE
sed -i -e "/provider.address=/c provider.address=" $CONF_FILE
