
class OceanContracts:
    OCEAN_MARKET_CONTRACT = 'Market'
    OCEAN_TOKEN_CONTRACT = 'OceanToken'
    OCEAN_ACL_CONTRACT = 'Auth'

    OMKT = OCEAN_MARKET_CONTRACT
    OTKN = OCEAN_TOKEN_CONTRACT
    OACL = OCEAN_ACL_CONTRACT